# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FaveoHelpdeskPro_ObjC' do
  
   pod 'NSDate-Time-Ago'
   pod 'HexColors'
   pod 'IQKeyboardManager'

endpod 